---

- name: install zabbix-agent
  yum: name=zabbix22-agent state=present
  
- name: write zabbix_agentd config file
  template: src=zabbix22-agent.j2 dest=/etc/zabbix_agentd.conf
  notify:
    - restart zabbix agent

