---

- name: Create the epel repo
  copy: src=epel.repo dest=/etc/yum.repos.d/epel.repo

- name: Create the GPG key For EPEL
  copy: src=RPM-GPG-KEY-EPEL-6 dest=/etc/pki/rpm-gpg

- name: yum dev group packages
  yum: name="@Development Tools"

- name: install some tools package
  yum: name=lrzsz state=present

- name: install some tools package
  yum: name=wget state=present

- name: install some tools package
  yum: name=vim-common state=present

- name: install some tools package
  yum: name=expect state=present

- name: install some tools package
  yum: name=epel-release state=present

- name: install some tools package
  yum: name=sysstat state=present

- name: install some tools package
  yum: name=lsof state=present

- name: install some tools package
  yum: name=libaio state=present

- name: install some tools package
  yum: name=baio-devel state=present

- name: install some tools package
  yum: name=screen state=present

- name: remove openjdk
  yum: name=java state=absent

- name: copy system file
  shell: cp /etc/fstab /etc/fstab.$(date +%F)

- name: copy system file
  shell: cp /etc/profile /etc/profile.$(date +%F)

- name: copy system file
  shell: cp /etc/passwd /etc/passwd.$(date +%F)

- name: copy system file on os family 5 or 6
  command: cp /boot/grub/grub.conf /boot/grub/grub.conf.$(date +%F)
  when: ansible_distribution_major_version != '7'

- name: copy system file on os family 7
  command: cp /boot/grub2/grub.cfg /boot/grub2/grub.cfg.bak
  when: ansible_distribution_major_version == '7'

- name: copy system file on os family 5 or 6
  shell: cp /etc/sysconfig/i18n /etc/sysconfig/i18n.$(date +%F) && echo -e 'LANG="zh_CN.UTF-8"\nLANG="en_US.UTF-8"\nSUPPORTED="zh_CN.UTF-8:zh_CN:zh:zh_TW.UTF-8:zh_TW:zh:en_US.UTF-8:en_US:en"\nSYSFONT="latarcyrheb-sun16"' > /etc/sysconfig/i18n
  when: ansible_distribution_major_version != '7'

- name: copy system file on os family 7
  shell: cp /etc/locale.conf /etc/locale.conf.$(date +%F) && echo -e 'LANG="zh_CN.UTF-8"\nLANG="en_US.UTF-8"\nSUPPORTED="zh_CN.UTF-8:zh_CN:zh:zh_TW.UTF-8:zh_TW:zh:en_US.UTF-8:en_US:en"\nSYSFONT="latarcyrheb-sun16"' > /etc/locale.conf
  when: ansible_distribution_major_version == '7'

# add tcp wrapper rule 
- name: cp hosts.deny shell to client
  copy: src=hosts_deny.sh dest=/tmp/hosts_deny.sh owner=root group=root mode=755

- name: add hosts.deny shell
  shell: /bin/bash /tmp/hosts_deny.sh

- name: add hosts.deny to crontab
  cron: name="hosts.deny" minute='*/5' job='/bin/sh /etc/hostsdeny.sh'

- name: add hosts.deny to crontab
  cron: name="clean" day="5" job="/bin/sh /etc/hostsdeny_clear.sh"

# modify some kernel parameter to sysctl.conf 
- name: sysctl
  sysctl: name=net.ipv4.tcp_tw_reuse value=1 sysctl_file=/etc/sysctl.conf  reload=yes

- name: sysctl
  sysctl: name=net.ipv4.tcp_tw_recycle value=1 sysctl_file=/etc/sysctl.conf  reload=yes

- name: sysctl
  sysctl: name=net.ipv4.tcp_timestamps value=0 sysctl_file=/etc/sysctl.conf  reload=yes

- name: sysctl
  sysctl: name=net.ipv4.tcp_fin_timeout value=30 sysctl_file=/etc/sysctl.conf  reload=yes

- name: sysctl
  sysctl: name=net.ipv4.tcp_keepalive_time value=120 sysctl_file=/etc/sysctl.conf  reload=yes

- name: sysctl
  sysctl: name=net.ipv4.ip_local_port_range value="10000 63000" sysctl_file=/etc/sysctl.conf  reload=yes

- name: sysctl
  sysctl: name=net.ipv4.tcp_max_syn_backlog value=8192 sysctl_file=/etc/sysctl.conf  reload=yes

- name: sysctl
  sysctl: name=net.ipv4.tcp_max_tw_buckets value=12000 sysctl_file=/etc/sysctl.conf  reload=yes

- name: copy system evn set to /etc/profile.d/
  copy: src=env_set.sh dest=/etc/profile.d/

- name: check limits.conf
  script: roles/common/files/check_ulimit.sh
